name: Clojure
on: [push]

jobs:
  clojure:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      # It is important to install java before installing clojure tools which needs java
      # exclusions: babashka, clj-kondo and cljstyle
      -
        name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      -
        name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.2
        with:
          cli: 1.11.1.1257             # Clojure CLI based on tools.deps
          clj-kondo: 2022.05.31        # Clj-kondo
          zprint: 1.2.3                # zprint
      # Optional step:
      -
        name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          # List all files containing dependencies:
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-
      -
        name: Get clj-kondo version
        run: clj-kondo --version
      # -
      #   name: Check outdated deps
      #   uses: liquidz/antq-action@main
      -
        name: Test
        run: clojure -X:test :dirs '["src/test"]'
      -
        name: Build
        run: clojure -T:build uber
      -
        name: Archive uberjar
        uses: actions/upload-artifact@v3
        with:
          name: uberjar
          path: target/patience.jar
      -
        name: Prepare uber to docker
        run: mv target/patience.jar docker/app.jar
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: docker
          push: true
          tags: "flawlesslt/patience:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max
